// get each html component by ID
const one = getelementById("one")
const two = getelementById("two")
const three = getelementById("three")
const four = getelementById("four")
const five = getelementById("five")
const six = getelementById("six")
const seven = getelementById("seven")
const eight = getelementById("eight")
const nine = getelementById("nine")
const zero = getelementById("zero")
const equal = getelementById("equal")
const decimal = getelementById("decimal")
const multiply = getelementById("multiply")
const divide = getelementById("divide")
const subtract = getelementById("subtract")
const add = getelementById("add")
cont display = getelementById("display")
